import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box, HStack, Input, Text, VStack } from "@chakra-ui/react";
import React, { useState } from "react";
import { ToHex } from "../components/ToHex";
import { ToDex } from "../components/ToDec";

const Home: NextPage = () => {
	const toDec = (hex: number | string) => {
		return parseInt(String(hex), 16);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<VStack spacing={10}>
					<ToHex></ToHex>
					<ToDex></ToDex>
				</VStack>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
};

export default Home;
