import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box, HStack, Input, Text, VStack } from "@chakra-ui/react";
import React, { useState } from "react";
import { ToHex } from "../components/ToHex";
import { ToSignedDec } from "../components/ToSignedDec";
import { ToSignedHex } from "../components/ToSignedHex";
import { ToUnsignedDec } from "../components/ToUnsignedDec";
import { ToUnsignedHex } from "../components/ToUnsignedHex";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<VStack spacing={10}>
					<ToHex></ToHex>
					<ToUnsignedDec></ToUnsignedDec>
					<ToSignedDec></ToSignedDec>
					<ToUnsignedHex></ToUnsignedHex>
					<ToSignedHex></ToSignedHex>
				</VStack>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
};

export default Home;
